<!-- #include file="begin.asp"-->


<!-- #include file="bs_security.asp"--><%logon.hasaccess secondAdmin.bIntranetSetup%><%cslist.list.remove(cs_silent)
dim postback
postback=convertBool(Request.Form ("postback"))
if postback then
customer.getIntranetAdminRequestValues()
end if
if Request.Form ("saveAdminIntranet")=l("save") then
checkCSRF()
customer.getIntranetAdminRequestValues()
if customer.save() then
message.Add ("fb_saveOK")
end if
end if%><!-- #include file="includes/header.asp"--><!-- #include file="bs_initBack.asp"--><!-- #include file="bs_header.asp"--><!-- #include file="includes/urlenCodeJS.asp"--><%=getBOHeader(btn_Intranet)%><%=getBOHeaderIntranet(btn_setupI)%><%if convertBool(customer.intranetUseMyProfile) then%><p align=center><b><a href="bs_adminIntranetOSM.asp"><%=l("onscreenmessages")%></a> - <a href="bs_adminIntranetEM.asp"><%=l("automatedemails")%></a></b></p><%end if%><form action="bs_adminIntranet.asp" name="mainform" method="post" onsubmit="javascript:return confirm('<%=l("areyousure")%>');"><input type="hidden" name="postback" value="<%=true%>" /><%=QS_secCodeHidden%><table align=center cellpadding="2"><tr><td class="header" colspan="2"><%=l("general")%>:</td></tr><tr><td class="QSlabel"><%=l("useintranet")%></td><td><input type=checkbox onclick="javascript:document.mainform.submit();" name="intranetUse" value="1" <%=convertChecked(customer.intranetUse)%> /></td></tr><%if convertBool(customer.intranetUse) then%><tr><td class="QSlabel"><%=l("name")%>:*</td><td><input name="intranetName" value="<%=quotRep(customer.intranetName)%>" type=text size=30 maxlength=49 /></td></tr><tr><td class="QSlabel"><%=l("labeleditsite")%>:*</td><td><input name="sLabelEditSite" value="<%=quotRep(customer.sLabelEditSite)%>" type=text size=30 maxlength=50 /></td></tr><tr><td class="QSlabel">User login-mode:*</td><td><select name="iLoginMode"><option value="0" <%if convertgetal(customer.iLoginMode)=0 then response.write "selected='selected'"%>><%=l("email")%></option><option value="1" <%if convertgetal(customer.iLoginMode)=1 then response.write "selected='selected'"%>><%=l("nickname")%></option></select></td></tr><tr><td class="QSlabel"><%=l("labellogoff")%>:*</td><td><input name="intranetLogOff" value="<%=quotRep(customer.intranetLogOff)%>" type=text size=30 maxlength=49 /></td></tr><tr><td class="QSlabel"><%=l("publicprofile")%></td><td><input type=checkbox onclick="javascript:document.mainform.submit();" name="intranetUseMyProfile" value="1" <%=convertChecked(customer.intranetUseMyProfile)%> /></td></tr><%if convertBool(customer.intranetUseMyProfile) then%><tr><td class="QSlabel"><%=l("labelmyprofile")%>:*</td><td><input name="intranetMyProfile" value="<%=quotRep(customer.intranetMyProfile)%>" type=text size=30 maxlength=49 /></td></tr><tr><td class="QSlabel">Use Avatars?</td><td><input type=checkbox onclick="javascript:document.mainform.submit();" name="bUseAvatars" value="1" <%=convertChecked(customer.bUseAvatars)%> /></td></tr><%if convertBool(customer.bUseAvatars) then
if convertGetal(customer.iAvatarSize)=0 then customer.iAvatarSize=80%><tr><td class="QSlabel">Avatar dimensions:</td><td><select name="iAvatarSize"><%=numberList(32,150,1,customer.iAvatarSize)%></select> px</td></tr><tr><td class="QSlabel">Avatar 1px border-color:</td><td><input type="text" maxlength="40" value="<%=quotrep(customer.sAvatarBorderColor)%>" name="sAvatarBorderColor" /> (leave blank for no border)</td></tr><%end if%><tr><td class="QSlabel"><%=l("allownewregistrations")%></td><td><input type=checkbox onclick="javascript:document.mainform.submit();" name="bAllowNewRegistrations" value="1" <%=convertChecked(customer.bAllowNewRegistrations)%> /></td></tr><%if convertBool(customer.bAllowNewRegistrations) then%><tr><td class="QSlabel" width="250"><%=l("defaultstatus")%>:*</td><td><select name="iDefaultStatus"><%=cslist.showSelected("option",customer.iDefaultStatus)%></select></td></tr><tr><td class="QSlabel"><%=l("labelregister")%>:*</td><td><input name="sLabelRegister" value="<%=quotRep(customer.sLabelRegister)%>" type=text size=50 maxlength=100 /></td></tr><tr><td class="QSlabel" width=250><%=l("sendmailuponnewmember")%></td><td><input type=checkbox onclick="javascript:document.mainform.submit();" name="bSendMailUponNewMember" value="1" <%=convertChecked(customer.bSendMailUponNewMember)%> /></td></tr><%if convertBool(customer.bSendMailUponNewMember) then%><tr><td class="QSlabel"><%=l("email")%>:*</td><td><input name="sEmailNewRegistrations" value="<%=quotRep(customer.sEmailNewRegistrations)%>" type="email" size=30 maxlength=50 /></td></tr><%end if
end if%><tr><td class="QSlabel" width="250">Notification-email for page-updates:</td><td><input name="sNotifValidate" value="<%=quotRep(customer.sNotifValidate)%>" type=text size=50 maxlength=100 /></td></tr><%end if%><tr><td class=QSlabel>&nbsp;</td><td>(*) <%=l("mandatory")%></td></tr><%end if%><tr><td class=QSlabel>&nbsp;</td><td><input class="art-button" type=submit name=saveAdminIntranet value="<%=l("save")%>" /></td></tr></table></form><!-- #include file="bs_endBack.asp"--><!-- #include file="includes/footer.asp"-->
