<!-- #include file="begin.asp"-->


<!-- #include file="bs_security.asp"--><%logon.hasaccess secondAdmin.bIntranetSetup%><!-- #include file="bs_process.asp"--><!-- #include file="includes/header.asp"--><!-- #include file="bs_initBack.asp"--><!-- #include file="bs_header.asp"--><!-- #include file="includes/urlenCodeJS.asp"--><%=getBOHeader(btn_Intranet)%><%=getBOHeaderIntranet(btn_setupI)%><%dim iMessages
set iMessages=customer.intranetMessages
set csShortList=new cls_contactStatusList
set csShortList=csShortList.list
csShortList.remove(cs_Silent)%><p align="center"><b><a href="bs_adminIntranetOSM.asp"><%=l("onscreenmessages")%></a> - <a href="bs_adminIntranet.asp"><%=l("back")%></a></b></p><form action="bs_adminIntranetEM.asp" name="mainform" method="post" onsubmit="javascript:return confirm('<%=l("areyousure")%>');"><%=QS_secCodeHidden%><input type=hidden name="btnaction" value="saveAdminIntranetEM" /><table align="center" width="700" cellpadding="2"><tr><td colspan="2"><%=l("explautomatedemails")%></td></tr><tr><td class="QSlabel"><%=l("mailsubjectregistrationticket")%>:</td><td><input name="sSubjectMailTicket" value="<%=quotRep(customer.sSubjectMailTicket)%>" type=text size=50 maxlength=100 /></td></tr><tr><td class="QSlabel" width="250"><%=l("mailbodyregistrationticket")%></td><td><%createFCKInstance customer.sMailTicket,"siteBuilderRichText","sMailTicket"%></td></tr><tr><td class="QSlabel" width="250"><%=l("textinemailpw")%>:</td><td><%createFCKInstance customer.intranetPWEmail,"siteBuilderRichText","intranetPWEmail"%></td></tr><tr><td class="QSlabel">&nbsp;</td><td><input  class="art-button" type="submit" name="dummy" value="<%=l("save")%>" /></td></tr><tr><td colspan="2"><hr /></td></tr><tr><td colspan="2"><%=l("explautomatedemailsonstatus")%></td></tr><%dim csKey
for each csKey in csShortList%><tr><td colspan=2><hr /></td></tr><tr><td class=QSlabel valign=top><b><%=csShortList(csKey)%></b>:</td><td valign=top><table><tr><td><%=l("subject")%></td><td><input type=text size=60 maxlength=100 name="sSubject<%=csKey%>" value="<%=quotrep(iMessages(csKey).sSubject)%>" /></td></tr><tr><td>HTML</td><td><%createFCKInstance iMessages(csKey).sBody,"siteBuilderRichText","sBody"&csKey%></td></tr><tr><td>Enabled?</td><td><input type=checkbox value="<%=true%>" name="bEnabled<%=csKey%>" <%=convertchecked(iMessages(csKey).bEnabled)%> /></td></tr><tr><td>&nbsp;</td><td><input class="art-button" type=submit name=dummy value="<%=l("save")%>" /></td></tr></table></td></tr><%next%></table></form><!-- #include file="bs_endBack.asp"--><!-- #include file="includes/footer.asp"-->
