<%
'thx to George Scott - www.officezilla.com

function showIcon(sIconName)	
	
	select case lcase(sIconName)
	
	case "asa"
		showIcon = "asa.gif"
	case "asp"
		showIcon = "asp.gif"
	case "avi"
		showIcon = "avi.gif"
	case "bat"
		showIcon = "bat.gif"
	case "bmp"
		showIcon = "bmp.gif"
	case "chm"
		showIcon = "chm.gif"
	case "com"
		showIcon = "com.gif"
	case "css"
		showIcon = "css.gif"
	case "dll"
		showIcon = "dll.gif"
	case "doc","docx"
		showIcon = "doc.gif"
	case "dwg"
		showIcon = "dwg.gif"
	case "dxf"
		showIcon = "dxf.gif"
	case "eml"
		showIcon = "eml.gif"
	case "exe"
		showIcon = "exe.gif"
	case "gif"
		showIcon = "gif.gif"
	case "hlp","help"
		showIcon = "hlp.gif"
	case "htm", "html"
		showIcon = "htm.gif"
	case "inc" 
		showIcon = "inc.gif"
	case "jbf" 
		showIcon = "jbf.gif"
	case "jpg","jp2","jpeg","jfif"
		showIcon = "jpg.gif"
	case "js" 
		showIcon = "js.gif"
	case "lnk" 
		showIcon = "lnk.gif"
	case "log" 
		showIcon = "log.gif"
	case "mdb" 
		showIcon = "mdb.gif"
	case "mid","midi"
		showIcon = "mid.gif"
	case "mov" 
		showIcon = "mov.gif"
	case "mp3" 
		showIcon = "mp3.gif"
	case "mpg","mpeg"
		showIcon = "mpg.gif"
	case "mpp" 
		showIcon = "mpp.gif"
	case "pdf" 
		showIcon = "pdf.gif"
	case "png" 
		showIcon = "png.gif" 
	case "ppt","pptx"
		showIcon = "ppt.gif" 
	case "psp" 
		showIcon = "psp.gif"
	case "pub" 
		showIcon = "pub.gif"
	case "qxd" 
		showIcon = "qxd.gif" 
	case "ram" 
		showIcon = "ram.gif"
	case "rar" 
		showIcon = "rar.gif"
	case "reg" 
		showIcon = "reg.gif"
	case "rtf" 
		showIcon = "rtf.gif" 
	case "sys" 
		showIcon = "sys.gif"
	case "txt" 
		showIcon = "txt.gif"
	case "vbs" 
		showIcon = "vbs.gif"
	case "vxd" 
		showIcon = "vxd.gif"
	case "wav" 
		showIcon = "wav.gif"
	case "wma" 
		showIcon = "wav.gif"
	case "wmv" 
		showIcon = "wav.gif"
	case "wri" 
		showIcon = "wri.gif"
	case "xls","xlsx"
		showIcon = "xls.gif"
	case "xml" 
		showIcon = "xml.gif"
	case "zip" 
		showIcon = "zip.gif"
	case "swf" 
		showIcon = "flash_icon.gif"
	case else
		showIcon = "unknown.gif"
	end select
	
	showIcon="<img src=" & """"  & C_DIRECTORY_QUICKERSITE & "/fixedImages/fileimages/" & showIcon & """" & " style=""margin-right:4px;border-style:none"" border=""0"" alt="""" align=""absmiddle"" />"

end function
%>